### ISSUE TITLE
retrying account creation but no one created  , i have proxies private premium , capmonster and api smspva

### ISSUE THREAD

**Issue by SooXenus** [broccosito/DiscordTokenGenerator#1]
✖ Discord API Error: Invalid Form Body
✖ Discord API Error: Invalid Form Body
ℹ Retrying account creation
ℹ Retrying account creation
✖ Discord API Error: Invalid Form Body
✖ Discord API Error: Invalid Form Body
ℹ Retrying account creation
✖ Discord API Error: Invalid Form Body
✖ Discord API Error: Invalid Form Body
✖ Discord API Error: Invalid Form Body
✖ Discord API Error: Invalid Form Body
⠦ Phone verification code sent
idk why if u can help me plz bro ,

**Comment by SooXenus** [comment]
error solved , can u tell me who can i put more thread ? i have only one per one

**Comment by SooXenus** [comment]
@broccosito

**Comment by broccosito** [comment]
@SooXenus lil brocco#6234, shoot me a DM and I'll help you
